#!/bin/bash
ocperf.py stat -e \
cpu_clk_unhalted.thread_p_any,\
dtlb_store_misses.stlb_hit,\
dtlb_store_misses.walk_duration,\
dtlb_load_misses.stlb_hit,\
dtlb_load_misses.walk_duration,\
icache.misses,\
idq.empty,\
idq_uops_not_delivered.core,\
ild_stall.iq_full,\
ild_stall.lcp,\
inst_retired.any,\
int_misc.recovery_cycles,\
itlb_misses.stlb_hit,\
itlb_misses.walk_duration,\
ld_blocks.store_forward,\
ld_blocks_partial.address_alias,\
mem_load_uops_llc_hit_retired.xsnp_hit,\
mem_load_uops_llc_hit_retired.xsnp_hitm,\
mem_load_uops_llc_miss_retired.local_dram,\
mem_load_uops_retired.l1_hit,\
mem_load_uops_retired.l2_hit,\
mem_load_uops_retired.llc_hit,\
mem_load_uops_retired.llc_miss,\
mem_uops_retired.split_loads,\
mem_uops_retired.split_stores,\
offcore_response.demand_code_rd.llc_miss.remote_dram,\
offcore_response.demand_data_rd.llc_miss.remote_dram,\
offcore_response.all_data_rd.any_response,\
offcore_response.pf_l2_data_rd.llc_hit.any_response,\
offcore_response.pf_l2_data_rd.llc_miss.any_response,\
offcore_response.pf_llc_data_rd.llc_hit.any_response,\
offcore_response.pf_llc_data_rd.llc_miss.any_response,\
partial_rat_stalls.flags_merge_uop_cycles,\
partial_rat_stalls.slow_lea_window,\
uops_issued.any,\
uops_retired.core_stall_cycles,\
uops_retired.retire_slots,\
stalled-cycles-frontend,\
stalled-cycles-backend -p $1 -o $2 -a sleep 30
