/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_overseerJNI_WrapperJNI */

#ifndef _Included_ch_usi_overseer_OverAgent
#define _Included_ch_usi_overseer_OverAgent
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jfloat JNICALL Java_ch_usi_overseer_OverAgent_getThreadCpuUsage
  (JNIEnv *, jobject, jint);

JNIEXPORT jfloat JNICALL Java_ch_usi_overseer_OverAgent_getThreadCpuUsageRelative
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_ch_usi_overseer_OverAgent_updateStats
  (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_ch_usi_overseer_OverAgent_isRunning
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_ch_usi_overseer_OverAgent_getVersion
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_ch_usi_overseer_OverAgent_getNumberOfThreads
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_ch_usi_overseer_OverAgent_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

